import Foundation

enum SSHKeys {
    static func publicKey() throws -> String {
        if !fileExists(Paths.sshKey) {
            Log.info("Generating SSH key \(Paths.sshKey.path)")
            try sh(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "orbshark", "-f", Paths.sshKey.path])
        }
        guard let pub = readString(Paths.sshPub) else { throw SharkError("cannot read \(Paths.sshPub.path)") }
        return pub
    }
}

enum SSHConfig {
    static let includeLine = "Include ~/.orbshark/ssh_config"

    /// The ProxyCommand that tunnels ssh over virtio-vsock (immune to VPNs/proxies capturing TCP on the Mac).
    static func proxyCommand(for m: Machine) -> String {
        "\(shellQuote(Paths.executable.path)) __proxy \(m.name)"
    }

    /// Base ssh arguments for talking to a machine.
    static func args(for m: Machine) -> [String] {
        [
            "ssh",
            "-i", Paths.sshKey.path,
            "-o", "IdentitiesOnly=yes",
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "LogLevel=ERROR",
            "-o", "ProxyCommand=\(proxyCommand(for: m))",
            "-o", "ControlMaster=auto",
            "-o", "ControlPath=\(Paths.root.path)/cm-%C",
            "-o", "ControlPersist=120",
            "\(m.config.user)@\(m.name).shark",
        ]
    }

    /// Arguments for a one-off readiness probe: fresh connection, never touches the mux master.
    static func probeArgs(for m: Machine) -> [String] {
        args(for: m).map { $0.hasPrefix("ControlMaster=") ? "ControlMaster=no" : ($0.hasPrefix("ControlPath=") ? "ControlPath=none" : $0) }
            + ["-o", "BatchMode=yes", "-o", "ConnectTimeout=5"]
    }

    /// Kill a lingering multiplex master for this machine (e.g. after the VM stopped).
    static func closeMux(for m: Machine) {
        _ = try? sh(["ssh", "-O", "exit", "-o", "ControlPath=\(Paths.root.path)/cm-%C", "\(m.config.user)@\(m.name).shark"], check: false, timeout: 5)
    }

    /// Regenerate ~/.orbshark/ssh_config with a `Host <name>.shark` entry per machine.
    static func update() {
        var out = "# Generated by OrbShark — edits will be overwritten.\n"
        out += "# Add `\(includeLine)` to ~/.ssh/config, then: ssh <machine>.shark\n\n"
        for m in Machine.all() {
            out += """
            Host \(m.name).shark
              User \(m.config.user)
              ProxyCommand \(proxyCommand(for: m))
              IdentityFile \(Paths.sshKey.path)
              IdentitiesOnly yes
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
              LogLevel ERROR

            """
        }
        writeString(out, to: Paths.sshConfig)
    }

    /// Ensure ~/.ssh/config includes our generated file. Returns true if it changed anything.
    @discardableResult
    static func install() throws -> Bool {
        let sshDir = Paths.home.appendingPathComponent(".ssh")
        let cfg = sshDir.appendingPathComponent("config")
        let existing = (try? String(contentsOf: cfg, encoding: .utf8)) ?? ""
        if existing.contains(includeLine) { return false }
        try FileManager.default.createDirectory(at: sshDir, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        if !existing.isEmpty {
            try? FileManager.default.copyItem(at: cfg, to: sshDir.appendingPathComponent("config.orbshark-backup"))
        }
        let new = "\(includeLine)\n" + (existing.isEmpty ? "" : "\n" + existing)
        try new.write(to: cfg, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: cfg.path)
        return true
    }
}
